openapi: 3.0.4
info:
  title: Designing API example
  description: |-
    Designing API example for learning purposes.
  version: 0.0.1
paths:
    /products:
        description: The products catalog
        get:
            summary: Search for products
            description: |
                Search for products in catalog
                using a free query parameter
            parameters:
              - name: free-query
                description: |
                    A product's name, reference, or partial description
                in: query
                required: false
                schema:
                    type: string
            responses:
                "200":
                    description: Products matching free query
                    content:
                        application/json:
                            schema:
                                type: array
                                items:
                                    required:
                                        - reference
                                        - name
                                        - price
                                        - supplier
                                    properties:
                                        reference:
                                            type: string
                                        name:
                                            type: string
                                        price:
                                            type: number
                                        descriptions:
                                            type: string
                                        supplier:
                                            type: object
                                            description: Product's supplier
                                            required:
                                                - reference
                                                - name
                                            properties:
                                                reference:
                                                    type: string
                                                    description: Supplier's unique identifier
                                                    example: MANPUB
                                                name:
                                                    type: string
                                                    example: Manning Publications
        post:
            summary: Add product
            description: |
                Add product (described in product info
                parameter) to catalog
            requestBody:
                description: Product's information
                content:
                    application/json:
                        schema:
                            required:
                                - name
                                - price
                                - supplierReference
                            properties:
                                name:
                                    type: string
                                price:
                                    type: number
                                description:
                                    type: string
                                supplierReference:
                                    type: string
            responses:
                "201":
                    description: Product added to 
                    content:
                        application/json:
                            schema:
                                type: object
                                required:
                                    - reference
                                    - name
                                    - price
                                    - supplier
                                properties:
                                    reference:
                                        type: string
                                    name:
                                        type: string
                                    price:
                                        type: number
                                    descriptions:
                                        type: string
                                    supplier:
                                        type: object
                                        description: Product's supplier
                                        required:
                                            - reference
                                            - name
                                        properties:
                                            reference:
                                                type: string
                                                description: Supplier's unique identifier
                                                example: MANPUB
                                            name:
                                                type: string
                                                example: Manning Publications

    /products/{productId}:
        description: A product
        delete:
            summary: Delete a product
            parameters:
              - name: productId
                description: Product's reference
                in: path
                required: true
                schema:
                    type: string
            responses:
                "204":
                    description: Product deleted